/* ==========================================================================
   PIZZABURG · HRM PRACTICES — deck data
   Group NEXIX · Bangladesh University · BUS-2204

   Every factual claim below traces to the group's own report, which rests on
   one face-to-face interview with Mr. Ranjan Datta, General Manager of Human
   Resource at PizzaBurg, on 26 August 2026, checked against the Bangladesh
   Labour Act 2006. Where the report says something was "not evidenced", the
   wording here keeps that distinction: nobody described it, which is not the
   same as it not existing.
   ========================================================================== */

const PRESENTERS = [
  { key: 'ratul',  name: 'Raiyan Ahmed Ratul',   short: 'Ratul',  id: '202511170047', hue: 8   },
  { key: 'aditto', name: 'Aditya Tripura',        short: 'Aditto', id: '202511170006', hue: 28  },
  { key: 'liya',   name: 'Liya Akter',            short: 'Liya',   id: '202511170072', hue: 44  },
  { key: 'souvo',  name: 'Shuvo Chandra Roy',     short: 'Souvo',  id: '202511170023', hue: 150 },
  { key: 'sourov', name: 'Asiful Islam Sourov',   short: 'Sourov', id: '202511170026', hue: 205 },
  { key: 'esha',   name: 'Fabliha Mubarrat Kabir',short: 'Esha',   id: '202511170060', hue: 268 },
];

/* The world is a single continuous model. Zones are laid out along +X so that
   moving between them is a real journey rather than a cut. */
const ZONE_GAP = 132;
const ZONE_ORDER = [
  'street', 'map', 'meeting', 'units', 'kitchen', 'door', 'bridge',
  'quarters', 'ladder', 'loop', 'law', 'ledger', 'workshop', 'rooftop',
];
const ZONES = {};
ZONE_ORDER.forEach((id, i) => { ZONES[id] = { id, index: i, x: i * ZONE_GAP }; });

/* --------------------------------------------------------------------------
   Slides. `cam` is [posX, posY, posZ, lookX, lookY, lookZ] in zone-local
   space; the world adds the zone's own X offset.
   -------------------------------------------------------------------------- */
const SLIDES = [

  /* ===== BLOCK A — RATUL ================================================= */
  {
    id: 'cover', by: 'ratul', zone: 'street', layout: 'cover',
    stack: 0,
    cam: [0, 15, 62, 0, 9, 0], fov: 40,
    kicker: 'Human Resource Management · BUS-2204',
    title: 'PizzaBurg',
    titleSub: 'How a chain of 22 kitchens manages its people',
    lede: 'An analytical study built on one afternoon with the General Manager of Human Resource.',
    bullets: [
      { head: 'Group', body: 'NEXIX — six students, Department of Business Administration' },
      { head: 'Submitted to', body: 'Md. Hassan Talukdar, Associate Professor' },
      { head: 'Institution', body: 'Bangladesh University · Batch 70' },
      { head: 'Date', body: '28 August 2026' },
    ],
    visual: { kind: 'photo', src: 'hero-pizzas', caption: 'PizzaBurg, Mirpur · 26 August 2026' },
    notes: 'Good afternoon. We are group NEXIX, and our report is on the human resource practices of PizzaBurg — a Bangladeshi pizza and burger chain that has gone from one shop to twenty-two in eight years. Everything you are about to see comes out of one face-to-face meeting with their General Manager of Human Resource, checked against the Bangladesh Labour Act. I will start with why we picked this company at all.',
  },
  {
    id: 'why', by: 'ratul', zone: 'street', layout: 'split',
    stack: 0,
    cam: [-16, 7.5, 26, 2, 7, -4],
    kicker: 'Why this topic',
    title: 'The worker is the product',
    lede: 'In a factory a manager catches a bad product before the buyer sees it. In a restaurant he cannot.',
    bullets: [
      { head: 'No safety net', body: 'The worker and the food reach the customer at the same moment' },
      { head: 'HR is visible', body: 'A late pizza or a rude counter reads as the whole brand' },
      { head: 'Local, not textbook', body: 'A Bangladeshi firm fighting foreign chains in the same city' },
      { head: 'Built while running', body: 'About 220 workers in 2020, close to 1,000 today' },
      { head: 'And we got in', body: 'The GM of Human Resource agreed to meet us face to face' },
    ],
    visual: { kind: 'photo', src: 'outlet-sign', caption: 'Inside a PizzaBurg outlet, Dhaka' },
    notes: 'Every business needs people, but restaurants are a special case. In a factory you can catch a defect before the customer sees it. In a restaurant the worker and the food arrive together, so how you treat your staff shows up on the plate. We wanted a local company rather than a textbook multinational, we wanted one that had grown fast enough for the strain to show, and honestly, we wanted one that would actually let us in. PizzaBurg was all three.',
  },
  {
    id: 'objectives', by: 'ratul', zone: 'map', layout: 'wide',
    stack: 0,
    cam: [0, 26, 46, 0, 2, -6],
    kicker: 'Objectives',
    title: 'Eight questions we took into the room',
    lede: 'One main aim: see how PizzaBurg manages its workers, and judge whether it fits how the business runs.',
    bullets: [
      { head: 'Staffing', body: 'How the company decides how many workers each outlet needs' },
      { head: 'Hiring', body: 'How kitchen and floor staff are recruited and chosen' },
      { head: 'Turnover', body: 'Who leaves, how often, and what the notice rule is for' },
      { head: 'Welfare', body: 'What workers get beyond wages' },
      { head: 'Performance', body: 'How work is checked and how that links to training' },
      { head: 'Discipline', body: 'What gets a worker dismissed — and against the Labour Act 2006' },
    ],
    photos: ['pizzaburg-menu-board', 'stock-city-street-daytime'],
    photoCaption: 'PizzaBurg’s own menu board · a Dhaka street',
    visual: { kind: 'objectives' },
    notes: 'Our main aim was to see how PizzaBurg manages its workers and to judge whether those methods fit the way the business actually runs. Underneath that we had eight smaller aims, and they became the six sections of our interview: staffing, hiring, turnover and notice, welfare, performance and training, and discipline. The last one was to compare all of it against the Bangladesh Labour Act 2006.',
  },
  {
    id: 'company', by: 'ratul', zone: 'map', layout: 'wide',
    stack: 0,
    cam: [10, 15, 30, -2, 1.5, -8],
    kicker: 'The company',
    title: 'One shop to twenty-two',
    lede: 'A business that grows this fast has to build its people systems while it is still running.',
    stats: [
      { value: '22', label: 'outlets' },
      { value: '~1,000', label: 'workers' },
      { value: '4,000+', label: 'pizzas a day' },
      { value: '2018', label: 'first shop, Mirpur-2' },
    ],
    bullets: [
      { head: 'Founded', body: 'January 2018 by Mir Mehedi and his father, about 33 lakh taka' },
      { head: 'Profitable fast', body: 'The first shop was in profit within four months' },
      { head: 'Twelve in Dhaka', body: 'The rest from Chattogram and Rajshahi to Feni and Noakhali' },
      { head: 'Mixed formats', body: 'Sit-down restaurants and delivery-only kitchens' },
      { head: 'A crowded trade', body: 'About 436,274 food outlets counted in 2021, and a very young population' },
    ],
    photos: ['pizzaburg-dailyasianage-feature', 'pizzaburg-combo-platter'],
    photoCaption: 'PizzaBurg in the press, and on the table',
    visual: { kind: 'timeline' },
    notes: 'PizzaBurg opened in Mirpur-2 in January 2018 with about thirty-three lakh taka, and it was profitable in four months. Seven shops by 2020, twenty-two today, close to a thousand workers, over four thousand pizzas a day. Twelve of those outlets are in Dhaka and the rest are spread from Chattogram to Noakhali. Hold on to that spread — it matters later, because a Dhaka shop that loses a cook can borrow one and a shop in Feni cannot.',
  },
  {
    id: 'scope', by: 'ratul', zone: 'map', layout: 'split',
    stack: 0,
    cam: [-18, 11, 24, 4, 2, -10],
    kicker: 'Scope',
    title: 'What this covers, and what it does not',
    lede: 'We are honest about the edges of this study, because the edges are wide.',
    bullets: [
      { head: 'Inside', body: 'Staffing, hiring, turnover, notice, welfare, performance, training, discipline' },
      { head: 'Outside', body: 'Profit, sales, marketing, supply chain, food safety systems' },
      { head: 'Head office only', body: 'Company policy, not a check of what every branch actually does' },
      { head: 'No documents', body: 'No appointment letter, service rules, appraisal form or training record' },
      { head: 'No workers', body: 'We did not interview a single ordinary employee' },
    ],
    photos: ['pizzaburg-menu-price-review'],
    photoCaption: 'What the company actually sells',
    visual: { kind: 'scope' },
    notes: 'We stayed on the HR side of the business — staffing, hiring, turnover, notice, welfare, performance, training and discipline. We did not look at profit or marketing or supply chain, and we did not ask for salary figures. Two limits matter most. This is head office policy, not a check of every branch. And we saw no documents and spoke to no ordinary worker. So when we say later that something was not evidenced, we mean nobody mentioned it to us. It may still exist.',
  },

  /* ===== BLOCK B — ADITTO ================================================ */
  {
    id: 'method', by: 'aditto', zone: 'meeting', layout: 'splitR', handover: true,
    stack: 0,
    cam: [-4, 6.5, 24, 0, 4.5, -2],
    kicker: 'Methodology',
    title: 'One room, one afternoon',
    lede: 'We wanted reasons, not numbers — and only the person who set the rule can explain it.',
    bullets: [
      { head: 'Design', body: 'A qualitative case study of one company, not a survey' },
      { head: 'Source', body: 'Mr. Ranjan Datta, General Manager of Human Resource' },
      { head: 'When', body: 'Face to face in Dhaka, 26 August 2026' },
      { head: 'Record', body: 'Handwritten notes — he preferred no recording' },
      { head: 'The caveat', body: 'He is the right witness to policy, not to daily practice in 22 shops' },
    ],
    visual: { kind: 'video', src: 'interview-18s', poster: 'interview-wide', caption: 'The interview, 26 August 2026' },
    notes: 'We could have surveyed workers. We did not, for two reasons. Our questions were about why the company does things a certain way, and a survey gives you numbers rather than reasons. And the access we had was to a senior manager. We used prepared questions but let ourselves follow up, and that mattered — the reason behind the two month notice rule came out of a follow-up, not from our written list. One caution: Mr. Datta is the right person to tell us what the policy is. He is not a neutral witness to how well it works at outlet level.',
  },
  {
    id: 'verify', by: 'aditto', zone: 'meeting', layout: 'wide',
    stack: 0,
    cam: [12, 8, 18, -2, 4, -6],
    kicker: 'Verification',
    title: 'Everything rests on one person',
    lede: 'So we tested him twice — once against himself, once against the outside world.',
    bullets: [
      { head: 'Internal check', body: 'We looked for contradictions across his own answers and found none' },
      { head: 'It hangs together', body: 'Fixed staffing, the notice rule and the turnover gap all explain each other' },
      { head: 'External check', body: 'Four claims tested against news reports and the Labour Act' },
      { head: 'The useful one', body: '22 outlets is exact, checkable, and nobody guesses that by accident' },
    ],
    photos: ['interview-manager', 'interview-team'],
    photoCaption: 'The meeting, 26 August 2026',
    visual: { kind: 'verify' },
    notes: 'Because everything rests on one person, we tested him twice. First internally — we looked for contradictions inside his own answers and found none. His reason for the notice rule fits the fixed staffing model, and both fit the gap he described between office and floor turnover. Then externally. The outlet number is the useful one: it is exact, it is checkable, and nobody guesses twenty-two correctly by accident. Finding it confirmed in a separate news report made us more willing to trust the parts we could not check.',
  },
  {
    id: 'staffing', by: 'aditto', zone: 'units', layout: 'split',
    stack: 1,
    cam: [-30, 20, 44, 6, 3, -6],
    kicker: 'Workforce planning',
    title: 'Twenty-two outlets, one fixed number',
    lede: 'Each outlet gets a set headcount. The company does not raise or lower it with demand.',
    stats: [
      { value: '22', label: 'outlets' },
      { value: 'Fixed', label: 'headcount each' },
      { value: 'No', label: 'demand-based flexing' },
    ],
    bullets: [
      { head: 'His words', body: 'The number is simply fixed for each shop' },
      { head: 'Not accidental', body: 'He was clear it is not set by supply and demand' },
      { head: 'A real choice', body: 'This is one of the two standard ways to plan manpower' },
      { head: 'The founder’s shadow', body: 'His first venture failed over partners — this one controls staffing tightly' },
    ],
    photos: ['stock-counter-cashier-restaurant', 'pizzaburg-bizfindly-listing'],
    photoCaption: 'A counter, and a fixed team behind it',
    visual: { kind: 'units' },
    notes: 'PizzaBurg runs twenty-two outlets and each one gets a fixed number of workers. Mr. Datta was clear that this number is not set by looking at supply and demand — it is simply fixed for each shop. That is a real choice, not an oversight. There are two standard ways to plan manpower: flex the number with demand, or fix it and keep it there. PizzaBurg has picked the second, and the next slide is what that buys them and what it costs them.',
  },
  {
    id: 'tradeoff', by: 'aditto', zone: 'units', layout: 'wide',
    stack: 1,
    cam: [0, 13, 34, 0, 3, -10],
    kicker: 'The trade-off',
    title: 'What a fixed number buys, and costs',
    lede: 'Neither method is better in general. This one is a fair choice for a chain that is still expanding.',
    photos: ['stock-counter-cashier-cafe'],
    photoCaption: 'The same service, every branch',
    visual: { kind: 'tradeoff' },
    bullets: [
      { head: 'Cost', body: 'Predictable and budgetable — but it does not fall in a slow month' },
      { head: 'Admin', body: 'Rosters and payroll stay simple — but the company reacts slowly' },
      { head: 'The team', body: 'The same people learn each other’s pace — but no hands for a rush' },
      { head: 'Customers', body: 'Service feels the same everywhere — assuming every shop is equally busy' },
      { head: 'Workers', body: 'Fixed hours and steady pay, better than most of this industry offers' },
    ],
    notes: 'Look at this honestly. On cost, a fixed number is easy to budget, but it does not drop in a slow month — you pay for idle time. Admin stays simple but reacts slowly. The team benefits, because the same people learn each other\'s pace, but there is no way to add hands for a rush. And the workers actually gain: fixed hours and steady pay is more than most of this industry offers. So the rule is defensible. Our problem is with something else.',
  },
  {
    id: 'untested', by: 'aditto', zone: 'units', layout: 'feature',
    stack: 2,
    cam: [26, 9, 22, -6, 2.5, -14],
    kicker: 'Our view',
    title: 'Nobody tests the number',
    lede: 'A headcount set on opening day stays right only while the shop stays the same.',
    bullets: [
      { head: 'It drifts silently', body: 'Delivery grows, a rival opens, a mall changes hours — nobody notices' },
      { head: 'One size, ten towns', body: 'Twelve Dhaka shops and ten scattered ones do not face the same demand' },
      { head: 'Or the same market', body: 'A Dhaka cook can be replaced in a week. A Feni cook cannot.' },
      { head: 'The fix is cheap', body: 'Twice a year, compare the number against orders, delivery share and overtime' },
    ],
    photos: ['stock-delivery-rider-motorcycle-city'],
    photoCaption: 'Delivery grew. The headcount did not move.',
    visual: { kind: 'drift' },
    notes: 'Here is the real question. It is not whether a fixed number is a good idea — it is whether the number is still the right one, and whether anybody checks. A number set on opening day only stays correct while conditions stay the same. If a branch picks up delivery orders, or a rival opens next door, the fixed number quietly becomes wrong, and nobody notices until service breaks or money is wasted. Nothing in the interview suggested these numbers are ever reviewed. Twice a year would fix it, and it costs nothing.',
  },

  /* ===== BLOCK C — LIYA ================================================== */
  {
    id: 'hiring', by: 'liya', zone: 'kitchen', layout: 'split', handover: true,
    stack: 3,
    cam: [-20, 8, 30, 2, 5, -4],
    kicker: 'Recruitment',
    title: 'Hired in a day',
    lede: 'The moment a cook quits the shop is short-handed, so speed here is not laziness. It is the only option.',
    stats: [
      { value: '1 day', label: 'application to offer' },
      { value: 'Experience', body: '', label: 'checked first' },
    ],
    bullets: [
      { head: 'One day', body: 'Interview, assessment and decision inside a single day' },
      { head: 'Experience first', body: 'The company looks at what practical work the person has already done' },
      { head: 'Then a test', body: 'Candidates may be asked to show what they can do' },
      { head: 'Why the rush', body: 'Every extra day of interviewing is another slow shift for everyone else' },
      { head: 'And the market', body: 'A cook looking for work takes the first decent offer' },
    ],
    photos: ['stock-interview-handshake-office', 'stock-chefs-kitchen-modern'],
    photoCaption: 'Interview and kitchen, on the same day',
    visual: { kind: 'funnel' },
    notes: 'Hiring for kitchen and floor jobs is done in one day. That sounds careless until you think about it from the shop\'s side. The moment a cook quits, the station is empty, and every extra day of interviewing is another day of slow service or overtime for everybody else. It also suits the candidate — a cook looking for work will not wait around while a slow company decides. He takes the first decent offer. Speed here is not laziness. It is the only way to catch good people at all.',
  },
  {
    id: 'worktest', by: 'liya', zone: 'kitchen', layout: 'feature',
    stack: 4,
    cam: [8, 5.5, 16, -4, 4, -8],
    kicker: 'The strongest thing in the system',
    title: 'Ask a cook to cook',
    lede: 'Watching somebody do the real task predicts job performance better than any interview or certificate.',
    bullets: [
      { head: 'The evidence', body: 'Work samples predict hands-on performance about as well as anything does' },
      { head: 'With a condition', body: 'Those findings are for standardised, scored exercises' },
      { head: 'And it has moved', body: 'Sackett and colleagues, 2022, put structured interviews at least level with them' },
      { head: 'Why it still fits here', body: 'The task is real, it is cheap, and candidates accept it as fair' },
      { head: 'Which sets up the gap', body: 'An unscored test inherits none of that measured validity' },
    ],
    photos: ['stock-dough-stretching-hands', 'stock-pizza-in-oven'],
    photoCaption: 'The test is the job itself',
    visual: { kind: 'worktest' },
    notes: 'This is, in our view, the single best thing in the whole system. Research on hiring keeps finding the same result for skilled hands-on jobs: watching someone do a real task from the job predicts performance far better than an ordinary interview or a look at their certificates. For a job where the skill is making food properly, fast, in heat, under pressure — watching the person do it tells you far more than talking about it. Whether PizzaBurg worked that out from theory or just from experience does not matter. It is the right method.',
  },
  {
    id: 'leak', by: 'liya', zone: 'kitchen', layout: 'split',
    stack: 5,
    cam: [22, 7, 20, -6, 4.5, -10],
    kicker: 'Where it leaks',
    title: 'A good test, marked by feeling',
    lede: 'A practical test only gives the same answer twice if the person watching marks against a fixed list.',
    bullets: [
      { head: 'No scoring sheet', body: 'Nothing written was described to us for judging the test' },
      { head: 'Two managers, two answers', body: 'The same pair of candidates, a different hire' },
      { head: 'The same manager drifts', body: 'He judges more softly on a day he is short of staff' },
      { head: 'And it is 22 shops', body: 'Policy is head office, hiring is done by operations managers' },
      { head: 'One page fixes it', body: 'Tasks, what to look for, a score out of five, a minimum to pass' },
    ],
    photos: ['stock-clipboard-person-holding'],
    photoCaption: 'The one page that is missing',
    visual: { kind: 'leak' },
    notes: 'The problem is at the marking stage. A practical test works because it is related to the job, but it only gives the same answer twice if the person watching is marking against a fixed list. Judge by feeling and two managers will pick different people from the same pair. The same manager will judge more softly on a day when he is short of staff. And remember this is happening at twenty-two shops, run by managers whose main job is operations. A one page checklist would hold the standard in place, and it would cost nothing.',
  },
  {
    id: 'turnover', by: 'liya', zone: 'door', layout: 'wide',
    stack: 6,
    cam: [0, 12, 34, 0, 6, -4],
    kicker: 'Turnover',
    title: 'Who stays, and who goes',
    lede: 'Office staff very low. Floor and kitchen staff medium. Those are his words, not a measurement.',
    bullets: [
      { head: 'Office: very low', body: 'Fewer similar jobs nearby, and a growing chain offers promotion' },
      { head: 'Floor: medium', body: 'Another employer within walking distance, and little lost by leaving' },
      { head: 'Young and part-time', body: 'Many are students who leave for exams or after graduating' },
      { head: 'Medium is respectable', body: 'His word, not a number — and we have no industry benchmark to test it against' },
      { head: 'But nobody counts it', body: 'Leavers over average headcount — the payroll already holds both numbers' },
      { head: 'And nobody asks why', body: 'Losing a weak worker and losing a good one look identical' },
    ],
    photos: ['stock-exit-box-belongings-office', 'stock-sous-chefs-kitchen'],
    photoCaption: 'Who walks, and who stays',
    visual: { kind: 'rings' },
    notes: 'On this one Mr. Datta answered in two words. Office turnover is very low, floor and kitchen turnover is medium. No figures. The gap is the interesting part and it matches fast food chains everywhere: a cook in Dhaka has options within a short walk, an accounts clerk does not. Medium is not a failure — given the industry it is quite respectable. But very low and medium are opinions, not measurements. Without a number the company cannot see a trend, cannot see which branch is worst, and cannot tell whether anything it changes has worked.',
  },
  {
    id: 'notice', by: 'liya', zone: 'bridge', layout: 'wide',
    stack: 7,
    cam: [-34, 11, 30, 10, 4, -2],
    kicker: 'The notice rule',
    title: 'Sixty days, half used',
    lede: 'A notice period does not keep anybody. It turns a sudden hole into a planned one.',
    stats: [
      { value: '2 months', label: 'company rule' },
      { value: '60 days', label: 's.27, permanent worker' },
      { value: '30 / 14', label: 'days if not permanent' },
    ],
    bullets: [
      { head: 'It matches one figure', body: 'Section 27 asks a permanent worker for 60 days written notice' },
      { head: 'But it is a worker’s duty', body: 'Not an employer duty, so it is not really a compliance win' },
      { head: 'And we never checked status', body: 'Nobody described classification, so we cannot say who is permanent' },
      { head: 'He gave an operational reason', body: 'He did not mention the Act, and we did not ask whether it was drawn from it' },
      { head: 'Worth what you do with it', body: 'Right now the 60 days is a cushion and nothing more' },
      { head: 'And it runs one way', body: 'Nobody asked what notice the company gives under Section 26' },
    ],
    photos: ['stock-calendar-desk-pen'],
    photoCaption: 'Sixty days, on a calendar',
    visual: { kind: 'days60' },
    notes: 'Every worker must give two months notice, and he told us why without being asked — it gives the company time to hire a replacement. Now here is something the interview never touched. Section 27 of the Labour Act asks a permanent worker for exactly sixty days written notice. PizzaBurg matches the statute precisely, apparently without realising. But a notice period does not keep anyone. It converts a sudden loss into a planned one, so its whole value is what you do with the sixty days — and right now it is only a cushion. Start hiring on day one and the leaver can train his own replacement before he walks out.',
  },

  /* ===== BLOCK D — SOUVO ================================================= */
  {
    id: 'welfare', by: 'souvo', zone: 'quarters', layout: 'wide', handover: true,
    stack: 8,
    cam: [0, 14, 36, 0, 4, -6],
    kicker: 'Welfare',
    title: 'Roof, meal, doctor, maternity',
    lede: 'Rent and food are the two biggest costs a low-paid Dhaka worker carries. PizzaBurg helps with both.',
    bullets: [
      { head: 'Housing help', body: 'Removes the single biggest cost of living in the city' },
      { head: 'Food help', body: 'Costs little in a business that already runs a kitchen' },
      { head: 'Health checkups', body: 'Care many low-paid workers would never pay for themselves' },
      { head: 'Maternity care', body: 'The point at which women most often leave a job' },
      { head: 'Worth more than a raise', body: 'The same money spent as a wage rise would buy less' },
      { head: 'And it fits the law', body: 'Sections 45 to 50 give 8 weeks before and 8 weeks after delivery' },
    ],
    photos: ['stock-bedroom-minimalist-bright', 'stock-canteen-group-eating', 'stock-stethoscope-hand'],
    photoCaption: 'Housing, food, health',
    visual: { kind: 'welfare' },
    notes: 'Workers who qualify get help with accommodation and food, health checkups, and maternity care. These are not small gestures. Rent and food are the two biggest costs a low-paid worker in Dhaka carries, and help with both is worth more to that worker than a small pay rise costing the company the same money. It also hits basic needs first, which is where motivation actually sits at these income levels. And maternity care is not just generosity — Sections 45 to 50 of the Labour Act make it a duty.',
  },
  {
    id: 'limits', by: 'souvo', zone: 'ladder', layout: 'split',
    stack: 9,
    cam: [-16, 15, 30, 4, 12, -6],
    kicker: 'The ceiling',
    title: 'Welfare stops unhappiness. It does not create drive.',
    lede: 'To move floor turnover from medium to low, the lever is a promotion ladder — not more benefits.',
    bullets: [
      { head: 'Herzberg on motivation', body: 'Hygiene factors remove dissatisfaction, they do not create drive' },
      { head: 'A different mechanism for staying', body: 'Tied housing raises the cost of leaving — side-bets, not satisfaction' },
      { head: 'Which is worth examining', body: 'A benefit that restricts mobility is not simply a benefit' },
      { head: 'Drive comes from', body: 'Being noticed, promoted, and seeing the path — expectancy, not perks' },
      { head: 'The jobs exist', body: 'A chain opening shops every year genuinely needs new supervisors' },
      { head: 'Four visible steps', body: 'Trainee, kitchen staff, senior kitchen staff, shift supervisor' },
      { head: 'One more gap', body: '"Eligible workers" — but the conditions were never explained to anyone' },
    ],
    photos: ['stock-team-huddle-closeup'],
    photoCaption: 'Promotion is the lever welfare cannot pull',
    visual: { kind: 'ladder' },
    notes: 'Here is the limit. Housing and food are what Herzberg would call hygiene factors: they stop workers being unhappy and they make leaving expensive, which probably explains why floor turnover is medium rather than high. What they do not do is make anyone work harder. Drive comes from being noticed and promoted. So if PizzaBurg wants floor turnover to go from medium to low, our reading is that more welfare is not the answer — a clear promotion path is. And in a company opening new shops every year, those supervisor jobs genuinely exist.',
  },
  {
    id: 'review', by: 'souvo', zone: 'loop', layout: 'split',
    stack: 10,
    cam: [-6, 13, 34, 2, 6, -4],
    kicker: 'Performance',
    title: 'Checked every month',
    lede: 'Better than we expected, and better than most of this industry manages.',
    stats: [
      { value: 'Monthly', label: 'not annual' },
      { value: '12×', label: 'a year' },
    ],
    bullets: [
      { head: 'The industry norm', body: 'Most firms this size check once a year — floor staff often never' },
      { head: 'Feedback lands early', body: 'The worker still remembers the shift it refers to' },
      { head: 'Problems show in weeks', body: 'Not at the end of a twelve month cycle' },
      { head: 'And the judgement is fair', body: 'The manager is judging one month he actually watched' },
      { head: 'It fits the work', body: 'Kitchen and service performance changes day to day and is visible all the time' },
    ],
    photos: ['stock-cooks-preparing-dough-team'],
    photoCaption: 'Judged on a month the manager actually watched',
    visual: { kind: 'cadence' },
    notes: 'Worker performance is checked every month. That was the whole answer, and it is better than we expected. Most companies this size check once a year, and in the restaurant trade floor staff are often never formally checked at all. Monthly means the feedback reaches the worker while he still remembers the shift. A slide in performance shows up in weeks instead of at year end. And the manager is judging one month he actually watched, rather than reconstructing twelve from memory. In a business where one bad shift is visible to customers, monthly is about right.',
  },
  {
    id: 'unanswered', by: 'souvo', zone: 'loop', layout: 'feature',
    stack: 11,
    cam: [16, 9, 22, -6, 5, -8],
    kicker: 'Two questions',
    title: 'Frequent is not the same as accurate',
    lede: 'What is actually being measured, and is any of it written down? The interview answered neither.',
    bullets: [
      { head: 'No fixed list', body: 'Nothing suggested a set of things the monthly check measures' },
      { head: 'The risk', body: 'A general impression twelve times a year is more frequent guesswork' },
      { head: 'No record described', body: 'So no month can be compared with the next' },
      { head: 'And no evidence', body: 'A file of monthly reviews is exactly what makes a dismissal stand up' },
      { head: 'Be fair', body: 'Nobody told us forms do not exist. Nobody mentioned them either.' },
    ],
    photos: ['stock-laptop-spreadsheet-analyzing'],
    photoCaption: 'What a record would let you compare',
    visual: { kind: 'unanswered' },
    notes: 'Two questions remain and the interview answered neither. First, what exactly is being measured? Frequency matters less than whether the things judged are clear and job related. If the monthly check is really the outlet manager\'s general impression, then doing it twelve times a year makes the guesswork more frequent, not more accurate. Second, is any of it written down? Without a record the company cannot compare months, cannot show a pattern of poor work if a firing is challenged, and cannot tell whether training helped. To be fair — nobody told us forms do not exist. Nobody mentioned them either.',
  },
  {
    id: 'training', by: 'souvo', zone: 'loop', layout: 'wide',
    stack: 12,
    cam: [0, 22, 30, 0, 5, -8],
    kicker: 'Training',
    title: 'The nine best words in the interview',
    lede: '"Performance measurement is linked with training." That one sentence solves the step most companies skip.',
    bullets: [
      { head: 'The usual failure', body: 'Companies buy training because a budget existed, and it fixes nothing' },
      { head: 'What PizzaBurg does', body: 'The appraisal itself finds the gap that needs training' },
      { head: 'A self-testing loop', body: 'Next month’s review is a natural test of whether the training worked' },
      { head: 'One condition', body: 'You can only see improvement if two months can be compared' },
      { head: 'Three gaps', body: 'No induction described, no supervisor training, no training records' },
    ],
    photos: ['stock-whiteboard-explaining-man'],
    photoCaption: 'Training aimed at a gap the review found',
    visual: { kind: 'loopviz' },
    notes: 'Performance measurement is linked with training. Nine words, and it is the cleverest thing in the system. The usual failure in training is skipping the first step — companies buy training because it was available or because a budget had to be spent, and it fixes problems nobody had. By letting the performance check decide who needs training, PizzaBurg has made the appraisal do the job of finding the gap. And because the review comes round monthly, the next review is a natural test of whether the training worked. Most companies never get that far. But it only becomes real with records.',
  },

  /* ===== BLOCK E — SOUROV =============================================== */
  {
    id: 'discipline', by: 'sourov', zone: 'law', layout: 'split', handover: true,
    stack: 13,
    cam: [-30, 9, 34, 6, 7, -6],
    kicker: 'Discipline',
    title: 'Four grounds for dismissal',
    lede: 'The reasons are fair, proportionate, and mostly line up with Section 23 of the Labour Act.',
    bullets: [
      { head: 'Breaking rules', body: 'How a 22-shop chain keeps hygiene and service the same everywhere' },
      { head: 'Sexual harassment', body: 'Naming it at all is to the company’s credit — many chains do not' },
      { head: 'Dishonesty', body: 'Cash and stock pass through many hands in a food shop' },
      { head: 'Serious misconduct', body: 'A catch-all, which only works if the behaviour really is misconduct' },
      { head: 'He said "may"', body: 'Not that every violation ends in dismissal' },
    ],
    photos: ['stock-archive-stacks-paper-string'],
    photoCaption: 'Grounds are easy. Files are the hard part.',
    visual: { kind: 'grounds' },
    notes: 'A worker can be dismissed for breaking rules and regulations, for sexual harassment, for dishonesty and for other serious misconduct. The grounds themselves are sensible and they mostly line up with the misconduct list in Section 23. Naming sexual harassment deserves real credit — plenty of companies in this industry do not list it at all, and putting it on the list says the company treats worker safety as policy. One point of fairness: he said a worker may be dismissed, not that every violation ends in dismissal. But in discipline, how you do it matters as much as what you do.',
  },
  {
    id: 's24', by: 'sourov', zone: 'law', layout: 'wide',
    stack: 14,
    recoil: true, arc: 0.35,
    cam: [-8, 8, 24, 2, 7, -12],
    kicker: 'Bangladesh Labour Act 2006',
    title: 'Section 24 is not optional',
    lede: 'No punishment under Section 23 is valid unless five specific steps have been followed.',
    stats: [
      { value: '7', label: 'days minimum to explain' },
      { value: '60', label: 'days — the cap on suspension' },
    ],
    bullets: [
      { head: 'Allegations in writing', body: 'Recorded in writing, with a copy given to the worker' },
      { head: 'Not less than seven days', body: 'To explain himself before anything is decided' },
      { head: 'A hearing, then a finding', body: 'Guilt has to be established on enquiry, not asserted' },
      { head: 'Then formal approval', body: 'The employer or manager approves the order' },
      { head: 'The Rules add the rest', body: 'Equal representation on the enquiry comes from the Labour Rules 2015' },
      { head: 'Nothing like this was described', body: 'And no step-by-step warning system was described either' },
    ],
    photos: ['stock-gavel-scales-wooden-desk'],
    photoCaption: 'Bangladesh Labour Act 2006',
    visual: { kind: 'section24' },
    notes: 'Section 24 is very specific. No punishment is valid unless the charge is written down, the worker gets a copy and at least seven days to reply, he gets a hearing, an inquiry committee with equal numbers from both sides finishes within sixty days, and the employer approves the order. These are not polite extras. A dismissal done without them can be thrown out by the Labour Court no matter how strong the case was. An employer with good grounds and a weak procedure is in worse shape than one with a solid procedure — because the court may never even reach the facts.',
  },
  {
    id: 'harassment', by: 'sourov', zone: 'law', layout: 'feature',
    stack: 15,
    still: true, arc: 0.1, slow: true,
    cam: [12, 7, 20, -4, 6.5, -14],
    kicker: 'The most urgent finding in our report',
    title: 'A rule with nowhere to apply it',
    lede: 'PizzaBurg treats harassment as a firing offence but no complaint committee was described to us.',
    bullets: [
      { head: 'No statute exists', body: 'Bangladesh has no separate law on sexual harassment at work' },
      { head: 'The High Court filled it', body: 'BNWLA v. Government of Bangladesh, 2009 — binding directions' },
      { head: 'Every workplace', body: 'A committee headed by a woman, a majority of women, at least two outside members' },
      { head: 'Plus s.332 of the Act', body: 'Which already forbids indecent or discourteous behaviour towards a woman at work' },
      { head: 'Force of law', body: 'The directions bind until Parliament passes an act' },
      { head: 'Both sides lose', body: 'She has no proper channel. He gets no fair hearing.' },
      { head: 'And it is nearly free to fix', body: 'Urgent, very low cost, zero to one month' },
    ],
    visual: { kind: 'harassment' },
    notes: 'This is the one we would fix first. Because there is no separate law, the rules come from the 2009 High Court directions, which require every workplace — private included — to set up a complaint committee with outside members, investigate within set times, and keep matters confidential. Nothing in our interview suggested such a committee exists. So the company has a rule with nowhere to apply it. If a complaint were made tomorrow there is no committee to hear it. That hurts both sides: the woman complaining has nowhere proper to go, and the man accused gets no fair process, so whatever is decided can be attacked from either direction.',
  },
  {
    id: 'scorecard', by: 'sourov', zone: 'law', layout: 'wide',
    stack: 16,
    cam: [0, 20, 30, 0, 6, -14],
    kicker: 'Compliance',
    title: 'PizzaBurg against the Labour Act',
    lede: 'Two rows match. Two rows are urgent. The rest is simply unknown, and knowing is the point.',
    bullets: [
      { head: 'Not evidenced ≠ absent', body: 'Most rows are things nobody asked about in one interview' },
      { head: 'Where we have evidence', body: 'The company is fine — notice and maternity both fit the Act' },
      { head: 'The risk is procedure', body: 'Not intention' },
      { head: 'What we recommend', body: 'An internal audit against the Act 2006 and the Rules 2015, yearly' },
      { head: 'A caveat', body: 'We are business students, not lawyers — a labour lawyer should confirm this' },
    ],
    photos: ['stock-laptop-graphs-dashboard'],
    photoCaption: 'What an internal audit would look at',
    visual: { kind: 'scorecard' },
    notes: 'Here is the whole picture against the Act. Most rows are marked check — those are things nobody asked about, so the company may be fully in line and the answer is an internal look. Two rows are different. Section 24 and the harassment committee are positions PizzaBurg has taken that need a system behind them, and no system was described. Where we do have evidence — the notice rule and maternity care — the company is fine. The risk here is procedure, not intention. And we should say plainly: we are business students, not lawyers.',
  },
  {
    id: 'findings', by: 'sourov', zone: 'ledger', layout: 'feature',
    stack: 16,
    cam: [-14, 16, 36, 4, 3, -6],
    kicker: 'Main findings',
    title: 'Good at doing. Poor at recording.',
    lede: 'In every area we asked about, the method was sound and the paperwork was missing.',
    bullets: [
      { head: 'It is a design', body: 'Every rule serves one goal — keep the 22 kitchens open' },
      { head: 'Not a pile of habits', body: 'Fixed teams, fast hiring, notice, welfare, monthly checks — they fit together' },
      { head: 'A good test', body: 'with no marking sheet' },
      { head: 'Frequent reviews', body: 'with no fixed measures and no records mentioned' },
      { head: 'Turnover discussed', body: 'but never counted, and leavers never asked why' },
      { head: 'Firing grounds', body: 'with no Section 24 procedure and no harassment committee described' },
      { head: 'And one honest catch', body: 'We read his account as evidence of method, and his silence as evidence of no records' },
    ],
    photos: ['stock-pizza-peel-oven-baked'],
    photoCaption: 'The method works. The paperwork is missing.',
    visual: { kind: 'findings' },
    notes: 'Put it all together and two things come out. First, this is a design, not a pile of habits. Everything points one way — keep the shops open and running. Fixed teams, one-day hiring, a notice rule that stops sudden gaps, welfare that keeps people turning up, monthly checks that catch problems in weeks. Second, and this is the pattern: the company is good at doing and poor at recording. In every area the method was sound and the paperwork was missing. That is exactly what happens when a business grows faster than its office.',
  },

  /* ===== BLOCK F — ESHA ================================================== */
  {
    id: 'swot', by: 'esha', zone: 'ledger', layout: 'wide', handover: true,
    stack: 16,
    cam: [10, 22, 30, -2, 3, -10],
    kicker: 'Strengths and weaknesses',
    title: 'Every weakness is the same weakness',
    lede: 'The company does things well and does not write them down. That is the whole list.',
    bullets: [
      { head: 'Strengths', body: 'The practical test, monthly reviews, welfare, s.27 notice, a real HR post' },
      { head: 'Weaknesses', body: 'No s.24 procedure, no harassment committee, no counting, no records' },
      { head: 'Opportunities', body: 'A growing industry, a young workforce, and fixes that cost almost nothing' },
      { head: 'Threats', body: 'Labour Court cases, a mishandled harassment case, foreign chains taking cooks' },
      { head: 'The pairing that matters', body: 'The two costliest weaknesses line up with the two costliest threats' },
    ],
    visual: { kind: 'swot' },
    notes: 'This puts everything into one view. The strengths are real — the practical test, monthly reviews, welfare, a notice rule matching the statute, and a genuine HR post at head office, which many chains this size do not have. But look at the weaknesses: every single one is the same type. The company does something and does not write it down. And here is the pairing that matters. The two weaknesses with the biggest possible cost — no firing procedure and no harassment committee — line up exactly with the two threats with the biggest possible cost. That is why they come first.',
  },
  {
    id: 'recs1', by: 'esha', zone: 'workshop', layout: 'wide',
    stack: 16,
    cam: [-24, 12, 32, 6, 4, -6],
    kicker: 'Recommendations · 1 to 5',
    title: 'Start with the two that cost nothing',
    lede: 'Ten suggestions, listed in the order we would actually do them.',
    photos: ['stock-whiteboard-presenting-team'],
    photoCaption: 'Ten suggestions, in the order we would do them',
    visual: { kind: 'recs', from: 0 },
    bullets: [
      { head: '1 · Committee and procedure', body: 'Harassment committee, plus the Section 24 steps in writing' },
      { head: '2 · Central records', body: 'One file per worker — the one that makes all the others possible' },
      { head: '3 · Marking sheet', body: 'One page for the practical test, filed with the appointment' },
      { head: '4 · Monthly review form', body: 'A few visible measures, weighted, signed, sent to head office' },
      { head: '5 · Count turnover', body: 'Leavers over average headcount, per shop, rolling twelve months' },
    ],
    notes: 'We ended with ten suggestions, and we listed them in the order we would actually do them. The first is the harassment committee and a written firing procedure, together, because they are the same problem — the company has taken positions it has no machinery to carry out. Second is central records, and it comes early not because records are exciting but because review forms, turnover figures and training checks all need somewhere to live. Then the marking sheet, the monthly review form, and counting turnover. All five are low cost and quick.',
  },
  {
    id: 'recs2', by: 'esha', zone: 'workshop', layout: 'wide',
    stack: 16,
    cam: [8, 12, 26, -4, 4, -10],
    kicker: 'Recommendations · 6 to 10',
    title: 'Then get value from what already exists',
    lede: 'Most of these do not add a rule. They finish one the company has already made.',
    photos: ['stock-canteen-people-eating'],
    photoCaption: 'Most of these finish a rule already made',
    visual: { kind: 'recs', from: 5 },
    bullets: [
      { head: '6 · Use the 60 days', body: 'Hire by day 30, overlap for handover, exit interview by head office' },
      { head: '7 · Welfare sheet and ladder', body: 'Publish who qualifies, then build four steps to supervisor' },
      { head: '8 · Induction and next-job training', body: 'Three days on joining, and grow your own supervisors' },
      { head: '9 · Six-monthly staffing review', body: 'Test each fixed number against orders, delivery and overtime' },
      { head: '10 · Internal Labour Act check', body: 'Walk the practice through the Act, yearly, lawyer-confirmed' },
    ],
    notes: 'The second five are mostly about getting full value out of rules the company has already made. Use the sixty days properly — start replacing on day one so the leaver can train his own replacement, and have head office, not the worker\'s own manager, ask why he is going. Publish the welfare conditions and build a promotion ladder. Add induction in the first three days and a short supervisor course. Test the staffing numbers twice a year. And walk the whole practice through the Labour Act once a year with a lawyer.',
  },
  {
    id: 'priority', by: 'esha', zone: 'workshop', layout: 'wide',
    stack: 16,
    cam: [0, 26, 26, 0, 3, -12],
    kicker: 'Sequencing',
    title: 'What to do first',
    lede: 'The most urgent item is also one of the cheapest, so there is no money argument for putting it off.',
    bullets: [
      { head: 'Urgent, almost free', body: 'The committee and the disciplinary procedure — nought to one month' },
      { head: 'First enabler', body: 'Central records, because everything else needs somewhere to live' },
      { head: 'Quick wins', body: 'Marking sheet, review form and turnover counting — one to two months each' },
      { head: 'Then the slower ones', body: 'Promotion ladder, induction, staffing review, legal audit' },
      { head: 'Nothing here is expensive', body: 'Almost every fix is a piece of paper and a decision' },
    ],
    photos: ['pizzaburg-bangladeshpost-inline'],
    photoCaption: 'A growing brand, and a growing paperwork debt',
    visual: { kind: 'matrix' },
    notes: 'Two things about this order. The most urgent item is also one of the cheapest, so there is no money argument for putting it off — it is zero to one month and very low cost. And central records sits early not because it is exciting but because it makes the others possible. Beyond that the pattern is clear: almost every fix in this report is a piece of paper and a decision. This is not a company that needs to spend money. It is a company that needs to write things down.',
  },
  {
    id: 'conclusion', by: 'esha', zone: 'rooftop', layout: 'split',
    stack: 16,
    arc: 1.6,
    cam: [-14, 18, 34, 4, 10, -6],
    kicker: 'Conclusion',
    title: 'Write the system down',
    lede: 'A business the owner watches himself runs on judgement. A thousand workers in ten towns cannot.',
    bullets: [
      { head: 'One purpose', body: 'Every rule the manager described serves keeping 22 kitchens open' },
      { head: 'And it works', body: 'It carried the company from one shop to twenty-two in eight years' },
      { head: 'The gap is paperwork', body: 'Sound methods, missing records, in every area we studied' },
      { head: 'Two gaps are serious', body: 'Section 24 and the harassment committee — and both are cheap to close' },
      { head: 'The next job', body: 'Turn judgement into forms without losing the speed' },
      { head: 'Our honest limit', body: 'One person, one meeting, no documents, no workers' },
    ],
    visual: { kind: 'photo', src: 'team-street', caption: 'NEXIX on the way to the interview, Dhaka' },
    notes: 'PizzaBurg is at a point many successful Bangladeshi companies reach. A business the owner watches himself can run on judgement and on knowing everyone. With a thousand workers in ten towns, judgement has to be written into forms or it stops being the same judgement from shop to shop, and knowing everyone has to become records or it disappears. The job now is to build the paperwork without losing the speed. And one last word — we spoke to one person, once. Where we say something was not evidenced, we mean nobody told us. It may well exist.',
  },
  {
    id: 'references', by: 'esha', zone: 'rooftop', layout: 'wide',
    stack: 16,
    cam: [16, 20, 30, -4, 12, -10],
    kicker: 'Sources',
    title: 'What this rests on',
    lede: 'One interview, one statute, and the reading we did around them. We are business students, not lawyers.',
    bullets: [
      { head: 'Primary', body: 'Datta, R. (2026). Interview by Group NEXIX, 26 August 2026, Dhaka.' },
      { head: 'Statute', body: 'Bangladesh Labour Act 2006 (Act XLII of 2006), as amended 2013 and 2018.' },
      { head: 'Rules', body: 'Bangladesh Labour Rules 2015, as amended.' },
      { head: 'Case', body: 'BNWLA v. Government of Bangladesh, WP 5916 of 2008, 14 May 2009, 14 BLC (HCD) 694.' },
      { head: 'Theory', body: 'Maslow 1943; Herzberg 1968; Schmidt & Hunter 1998; Sackett et al. 2022; Dessler 2020.' },
      { head: 'Context', body: 'BBS Hotel and Restaurant Survey 2021; New Age 2020; Dhaka Socials 2026; Mordor 2026.' },
    ],
    visual: { kind: 'refs' },
    notes: 'Very quickly, this is what the report rests on. One interview with Mr. Ranjan Datta on the twenty-sixth of August. The Labour Act of 2006 as amended, and the Labour Rules of 2015. The 2009 High Court case on harassment. And the theory is standard course material — Maslow, Herzberg, and the selection research from Schmidt and Hunter, updated by Sackett and colleagues in 2022. One last thing we want to say plainly: we are business students, not lawyers, and PizzaBurg should have a labour practitioner check anything we have raised.',
  },
  {
    id: 'thanks', by: 'esha', zone: 'rooftop', layout: 'closing',
    stack: 16,
    arc: 1.4,
    cam: [0, 13, 40, 0, 11, -8], fov: 42,
    kicker: 'Group NEXIX',
    title: 'Thank you',
    titleSub: 'Questions and discussion',
    lede: 'With thanks to Mr. Ranjan Datta, who answered every question we asked — including the difficult ones.',
    bullets: [],
    visual: { kind: 'team' },
    notes: 'Thank you. Our biggest thanks go to Mr. Ranjan Datta, the General Manager of Human Resource at PizzaBurg, who gave us his time and answered every question we asked — including the ones about firing workers and about harassment. Students do not usually get that kind of access. Thanks also to our course teacher, Md. Hassan Talukdar, who let us pick our own company. We are happy to take questions.',
  },
];

/* The record stack. Each entry is one card that drops onto the plinth in the
   3D world as its slide arrives. `solid` is something the manager described;
   `hollow` is a claim with nothing behind it. By the last slide the stack is
   half air, which is the finding. */
const STACK_DROPS = [
  { at: 'staffing',   kind: 'solid',  what: '22 outlets, a fixed headcount each' },
  { at: 'untested',   kind: 'hollow', what: 'No review of that number' },
  { at: 'hiring',     kind: 'solid',  what: 'A one-day hiring process' },
  { at: 'worktest',   kind: 'solid',  what: 'A practical test' },
  { at: 'leak',       kind: 'hollow', what: 'No marking sheet for it' },
  { at: 'turnover',   kind: 'hollow', what: 'Turnover never counted' },
  { at: 'notice',     kind: 'solid',  what: 'Two months notice' },
  { at: 'welfare',    kind: 'solid',  what: 'Housing, food, health, maternity' },
  { at: 'limits',     kind: 'hollow', what: 'Eligibility never explained' },
  { at: 'review',     kind: 'solid',  what: 'A monthly performance check' },
  { at: 'unanswered', kind: 'hollow', what: 'No measures, no record' },
  { at: 'training',   kind: 'solid',  what: 'Training follows the check' },
  { at: 'discipline', kind: 'solid',  what: 'Four grounds for dismissal' },
  { at: 's24',        kind: 'hollow', what: 'No Section 24 procedure' },
  { at: 'harassment', kind: 'hollow', what: 'No complaint committee' },
  { at: 'scorecard',  kind: 'hollow', what: 'Most of the Act never tested' },
];

/* --- supporting data for the 2D visual components ------------------------- */

const TIMELINE = [
  { when: 'Jan 2018', what: 'First shop opens in Mirpur-2', staff: 'One shop. The owner watches everything himself.', n: 1 },
  { when: 'Mid 2018', what: 'Profitable in four months', staff: 'Confidence to open more and hire more.', n: 1 },
  { when: 'Late 2020', what: 'Seven places in Dhaka', staff: 'Around 220 workers. Managers take over.', n: 7 },
  { when: 'Late 2022', what: 'Nine in Dhaka plus Narayanganj', staff: 'First move outside Dhaka. Training must match everywhere.', n: 10 },
  { when: '2023–25', what: 'Other cities, delivery kitchens', staff: 'Different shop types need different staff mixes.', n: 16 },
  { when: '2026', what: '22 outlets, ~1,000 workers', staff: 'Too big to run on memory. Written systems become necessary.', n: 22 },
];

const OUTLET_CITIES = [
  { city: 'Dhaka', n: 12, note: 'Deep labour market. One shop can lend another a cook.' },
  { city: 'Chattogram', n: 2, note: 'Divisional city. More training done in house.' },
  { city: 'Narayanganj', n: 1, note: 'The first outlet outside Dhaka, 2022.' },
  { city: 'Cumilla', n: 1, note: 'District town. One leaver can break a shift.' },
  { city: 'Rajshahi', n: 1, note: 'Few trained cooks nearby.' },
  { city: 'Feni', n: 1, note: 'No branch close enough to lend staff.' },
  { city: 'Khulna', n: 1, note: 'Head office is far away.' },
  { city: 'Mymensingh', n: 1, note: 'Advance planning matters most here.' },
  { city: 'Barishal', n: 1, note: 'Replacements are hardest to find.' },
  { city: 'Noakhali', n: 1, note: '60 days notice may barely be enough.' },
];

const VERIFY_ROWS = [
  { point: 'Number of outlets', said: '22', source: 'A 2026 news report also says 22', result: 'Matches', good: true },
  { point: 'Two month notice', said: 'Two months required', source: 'Section 27 asks for 60 days', result: 'Matches the law', good: true },
  { point: 'Maternity care', said: 'Provided', source: 'Sections 45–50 give this right', result: 'Fits the law', good: true },
  { point: 'Young, part-time staff', said: 'Implied by medium floor turnover', source: 'News reports describe young student staff', result: 'Fits', good: true },
];

const TRADEOFF_ROWS = [
  { area: 'Cost', gain: 'Labour cost per shop is known in advance and easy to budget.', give: 'The cost does not drop in slow months. Idle time is paid for.' },
  { area: 'Office work', gain: 'Rosters and payroll stay simple across 22 shops.', give: 'Simple, but slow to react.' },
  { area: 'The team', gain: 'The same people learn each other’s pace. New staff settle faster.', give: 'No easy way to add hands for a short rush.' },
  { area: 'Customers', gain: 'Service feels the same at any branch, which protects the brand.', give: 'It assumes every shop is equally busy.' },
  { area: 'The workers', gain: 'Fixed hours and steady pay — better than most of the industry.', give: 'Rush pressure lands on the same fixed team.' },
  { area: 'New shops', gain: 'Easy to plan. A new outlet needs a known number of people.', give: 'Nothing corrects the number as a shop changes.' },
];

const HIRING_STEPS = [
  { step: 'Finding candidates', what: 'Not described to us.', note: 'Probably walk-in and word of mouth, as is normal in the trade.', status: 'unknown' },
  { step: 'Interview', what: 'Done within one day.', note: 'Right for the situation. We do not know if it follows a structure.', status: 'ok' },
  { step: 'Past experience', what: 'Looked at.', note: 'Fair and job related, though it does not prove present skill.', status: 'ok' },
  { step: 'Practical test', what: 'Candidate may be asked to show ability.', note: 'The best part of the system.', status: 'best' },
  { step: 'Marking', what: 'No scoring sheet was mentioned.', note: 'The weak point. This is where the test loses its value.', status: 'weak' },
  { step: 'Decision', what: 'Made after the test.', note: 'Fast, which keeps the shop running.', status: 'ok' },
];

const NOTICE_STAGES = [
  { day: '0', title: 'Notice given', body: 'Worker resigns in writing. Section 27 asks for 60 days.' },
  { day: '1–10', title: 'Vacancy confirmed', body: 'Hiring starts immediately instead of at the end.' },
  { day: '10–30', title: 'Candidates found', body: 'One-day interview and the practical test.' },
  { day: '30–50', title: 'Replacement settles in', body: 'New worker hired and learning the station.' },
  { day: '50–60', title: 'Overlap', body: 'The leaver trains the new person on this kitchen.' },
  { day: '60', title: 'No gap, and an answer', body: 'Worker leaves. Exit interview done by head office.' },
];

const WELFARE_ITEMS = [
  { icon: 'roof', name: 'Housing help', worker: 'Removes the biggest single cost of living in a city.', company: 'Real value without the same rise in the wage bill. Shorter travel, better attendance.' },
  { icon: 'bowl', name: 'Food help', worker: 'Cuts daily spending and guarantees a meal during a long shift.', company: 'Costs little in a business that already runs a kitchen. Visible every day.' },
  { icon: 'cross', name: 'Health checkups', worker: 'Care many low-paid workers would never pay for themselves.', company: 'Catches illness before it becomes absence.' },
  { icon: 'cradle', name: 'Maternity care', worker: 'Support during pregnancy and after.', company: 'Helps keep women workers. Fits Sections 45–50 of the Labour Act.' },
];

const LADDER_STEPS = [
  { name: 'Trainee', state: 'now' },
  { name: 'Kitchen staff', state: 'now' },
  { name: 'Senior kitchen staff', state: 'proposed' },
  { name: 'Shift supervisor', state: 'proposed' },
];

const GROUNDS = [
  { name: 'Breaking rules and regulations', why: 'Standard procedure is how a 22-shop chain keeps hygiene and service the same.', law: 'Matches s.23(4) — wilful disobedience and repeated rule breaking.' },
  { name: 'Sexual harassment', why: 'Protects worker safety and dignity, and the brand.', law: 'Engages s.332 and the 2009 High Court directions — a complaint committee is compulsory.' },
  { name: 'Dishonesty', why: 'Cash and stock pass through many hands in a food shop.', law: 'Matches theft and fraud under s.23(4).' },
  { name: 'Other serious misconduct', why: 'A catch-all for behaviour not listed above.', law: 'Broadly fits s.23(4), if the behaviour really is misconduct.' },
];

const S24_STEPS = [
  { n: 1, title: 'Allegations in writing', body: 'The charge is recorded in writing and a copy given to the worker.', src: 's.24(1)' },
  { n: 2, title: 'Not less than seven days', body: 'The worker gets at least seven days to explain himself.', src: 's.24(1)' },
  { n: 3, title: 'An opportunity to be heard', body: 'The worker must be heard before anything is decided.', src: 's.24(1)' },
  { n: 4, title: 'Guilt found on enquiry', body: 'An enquiry has to establish the misconduct — assertion is not enough.', src: 's.24(1)' },
  { n: 5, title: 'The order approved', body: 'The employer or manager must approve the punishment order.', src: 's.24(1)' },
  { n: 6, title: 'And how the enquiry is run', body: 'Equal employer and worker representation, and the worker may be assisted.', src: 'Labour Rules 2015' },
];

const SCORECARD = [
  { sec: 's.4', asks: 'Workers classified — apprentice, casual, temporary, probationer, permanent.', found: 'Never discussed, so we cannot show any worker is permanent.', status: 'unknown', priority: 'Check' },
  { sec: 's.5', asks: 'An appointment letter and a photo ID card for every worker.', found: 'Appointment mentioned, no paperwork described.', status: 'unknown', priority: 'Check' },
  { sec: 'ss.6–9', asks: 'A service book and a register of workers.', found: 'Not discussed. This is what makes our records fix a legal duty.', status: 'unknown', priority: 'Check' },
  { sec: 's.23', asks: 'Dismissal allowed for conviction or for listed misconduct.', found: 'The grounds named to us broadly match the list.', status: 'match', priority: 'Low' },
  { sec: 's.24 + Rules 2015', asks: 'Written charge, 7 days to explain, a hearing, guilt found on enquiry, approval.', found: 'No such procedure was described.', status: 'urgent', priority: 'URGENT' },
  { sec: 's.26', asks: '120 or 60 days notice plus compensation to terminate without cause.', found: 'Not discussed. The company enforces notice one way only.', status: 'unknown', priority: 'Check' },
  { sec: 's.27', asks: 'A worker’s own duty — 60 days if permanent, 30 or 14 if not.', found: 'Two months asked of everyone. A worker duty, not an employer one.', status: 'partial', priority: 'Note' },
  { sec: 's.33', asks: 'A written grievance procedure with time limits and Labour Court recourse.', found: 'Not discussed. Our "no channel" claim depends on this too.', status: 'unknown', priority: 'Check' },
  { sec: 'ss.45–50', asks: 'Maternity benefit, 8 weeks before and 8 after, 6 months service.', found: 'Maternity care given. Nothing about the entitlement described.', status: 'unknown', priority: 'Check' },
  { sec: 'Ch. VIII', asks: 'First aid, canteen, child-care room, group insurance — by establishment size.', found: 'Never tested. We judged generosity without checking the floor.', status: 'unknown', priority: 'Check' },
  { sec: 's.205', asks: 'A participation committee where 50+ permanent workers are employed.', found: 'Not discussed.', status: 'unknown', priority: 'Check' },
  { sec: 's.332 + 2009 order', asks: 'Decent behaviour towards women, and a harassment complaint committee.', found: 'Harassment is a firing offence. No committee was described.', status: 'urgent', priority: 'URGENT' },
  { sec: 'ss.100–109', asks: 'Hours, overtime at double rate, weekly holiday, night work for women.', found: 'Not discussed, though 4am Ramadan opening is publicly reported.', status: 'unknown', priority: 'Check' },
];

const SWOT = {
  strengths: ['Practical test when hiring', 'One-day hiring process', 'Monthly performance checks', 'Training follows the check', 'Housing, food and health support', 'Notice rule matches Section 27', 'Office staff rarely leave', 'A real HR post at head office', 'Steady hours for workers', 'Harassment named as a firing offence'],
  weaknesses: ['No Section 24 firing procedure', 'No harassment complaint committee', 'Turnover never counted', 'Nobody asks why people leave', 'No marking sheet for the practical test', 'No fixed measures in the monthly check', 'Weak records across the board', 'Staffing numbers never reviewed', 'Welfare rules never explained', 'No promotion path', 'No induction for new joiners'],
  opportunities: ['A fast growing industry', 'A large young workforce', 'Welfare as a hiring pitch', 'Most fixes are just writing things down', 'Honest feedback from leavers', 'Cheap HR software available'],
  threats: ['Labour Court cases over dismissal', 'Damage from a mishandled harassment case', 'Foreign chains taking experienced cooks', 'Workers can leave at almost no cost', 'Growth outrunning the systems', 'Tighter enforcement of labour law'],
};

const RECOMMENDATIONS = [
  { n: '9.1',  title: 'Harassment committee and firing procedure', urgency: 'Urgent', cost: 'Very low', time: '0–1 month', gain: 'Removes the two biggest risks in the report.' },
  { n: '9.9',  title: 'Central records', urgency: 'High', cost: 'Low', time: '1–3 months', gain: 'Makes most of the other suggestions possible.' },
  { n: '9.3',  title: 'Marking sheet for the practical test', urgency: 'High', cost: 'Very low', time: '1 month', gain: 'The same hiring standard in all 22 shops.' },
  { n: '9.4',  title: 'Monthly review form', urgency: 'High', cost: 'Very low', time: '1–2 months', gain: 'Turns a frequent chat into usable evidence.' },
  { n: '9.5',  title: 'Count turnover every month', urgency: 'High', cost: 'Very low', time: '1 month', gain: 'Makes the retention problem visible.' },
  { n: '9.6',  title: 'Use the notice period properly', urgency: 'Medium', cost: 'Very low', time: '1–2 months', gain: 'Gets full value from a rule already in place.' },
  { n: '9.7',  title: 'Welfare sheet and promotion ladder', urgency: 'Medium', cost: 'Low', time: '2–4 months', gain: 'Better hiring appeal and lower floor turnover.' },
  { n: '9.8',  title: 'Induction and supervisor training', urgency: 'Medium', cost: 'Low–medium', time: '3–6 months', gain: 'Fewer early leavers and home-grown managers.' },
  { n: '9.2',  title: 'Six-monthly staffing review', urgency: 'Medium', cost: 'Very low', time: '6 months', gain: 'Stops the fixed number drifting out of date.' },
  { n: '9.10', title: 'Internal Labour Act check', urgency: 'Medium', cost: 'Low–medium', time: '3–6 months', gain: 'Confirms and proves compliance.' },
];

const OBJECTIVES = [
  'How the company decides how many workers each outlet needs',
  'How it hires kitchen and floor staff',
  'Who leaves the company, and how often',
  'What the two month notice rule is for',
  'What welfare the workers get',
  'How performance is checked, and how it links to training',
  'What gets a worker dismissed',
  'How all of it compares with the Bangladesh Labour Act 2006',
];

const SCOPE = {
  inside: ['Staffing and manpower planning', 'Recruitment and selection', 'Turnover and notice', 'Welfare and benefits', 'Performance and training', 'Discipline and dismissal', 'Compliance with the Labour Act 2006'],
  outside: ['Profit, sales and marketing', 'Social media and branding', 'Supply chain and food safety systems', 'Salary figures', 'Individual worker files', 'Branch-level practice', 'Any worker’s own view'],
};

const FINDINGS = {
  told: [
    '22 outlets, each with a fixed number of workers, not adjusted for how busy a shop is',
    'Office turnover very low. Floor and kitchen turnover medium. No figures given.',
    'Two months notice before resigning, so a replacement can be hired',
    'Kitchen and floor staff hired in one day, with experience checked and ability demonstrated',
    'Performance checked every month, not once a year',
    'What the performance check finds decides who gets training',
    'Housing, food, health checkups and maternity care for workers who qualify',
    'Dismissal for breaking rules, sexual harassment, dishonesty and other serious misconduct',
  ],
  concluded: [
    'Everything points at keeping the shops open. It is a design, not a pile of habits.',
    'The company is good at doing and poor at recording — on the eight things we asked about.',
    'The two month rule matches the Section 27 figure for a permanent worker, though nobody showed us who is permanent.',
    'The practical test is the best single thing, but without a marking sheet it loses consistency.',
    'Turnover is described but never measured, and leavers are never asked why.',
    'Welfare stops unhappiness. Cutting floor turnover needs a promotion path.',
    'No Section 24 procedure was described. A dismissal can be cancelled on process alone.',
    'No harassment committee was described. This is the most urgent thing we found.',
  ],
};
